version: "3.1"

services:
  github.com/yigittopm/go-auth:
    container_name: demo-go
    build: ./
    depends_on:
      - db
  db:
    container_name: demo-pg
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=analytic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
