version: '3.8'

services:
  api:
    build: ..
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - db
      - cache
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - /var/folders/go-auth:/var/lib/postgresql/data
  cache:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - db


